name: temp-bseed-stock-restore-build

on:
  push:
    branches:
      - chatgpt-stock-restore-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "workflow ok"
